"""External knowledge contracts for OAI-2.0.

The current package contains a tested application-level Cloudflare storage
contract, deterministic mock bindings, and a strict q-pipe import gate.
Live Cloudflare network wiring remains PROPOSED until a Worker transport is
implemented and verified against production-safe bindings.
"""

from __future__ import annotations

from .abstraction import (
    InMemoryKnowledgeStore,
    KnowledgeObject,
    KnowledgeStore,
    RetrievalRequest,
    RetrievalResult,
    now_epoch,
    sha256_hex,
)
from .cloudflare import (
    CFPlan,
    CFPrimitive,
    CFRow,
    CloudflareBindingAdapter,
    CloudflareKnowledgeStore,
    MockCloudflareBindings,
    cache_key_for,
    hash_topic,
    object_to_row,
    r2_blob_key_for,
)
from .gc import (
    GcDryRunReport,
    GcObjectDisposition,
    GcObjectRecord,
    GcReconciliationState,
    KnowledgeBlobRow,
    R2InventoryObject,
)
from .gc_lease import (
    GcDeleteFinalizeDecision,
    GcDeleteLease,
    GcDeleteLeaseAuthority,
    GcDeleteLeaseDecision,
    GcDeleteLeaseResult,
    GcDeleteLeaseState,
    GcReferenceDecision,
)
from .gc_lease_d1 import (
    GC_LEASE_ACQUIRE_SQL,
    GC_LEASE_REFERENCE_COUNT_SQL,
    GC_LEASE_SCHEMA_SQL,
    GC_LEASE_SCHEMA_VERSION,
    GC_LEASE_SELECT_SQL,
    GC_LEASE_TABLE,
    GC_LEASE_UPSERT_SQL,
    GC_LEASE_VALIDATE_SQL,
    GC_LEASE_WRITER_BLOCK_SQL,
    gc_lease_schema_statements,
)
from .gc_lease_d1_runtime import (
    D1DatabaseBinding,
    D1GcLeaseStore,
    D1PreparedStatementBinding,
)
from .ingestion import IngestionJob, IngestionPipeline, IngestionStatus
from .qpipe_import import (
    QPIPE_COMPATIBILITY_SOURCE_BLOBS,
    QPIPE_COMPATIBILITY_SOURCE_REVISION,
    ImportPolicy,
    ImportReport,
    QPipeRow,
    QPipeSource,
    QPipeStatus,
    derive_authority,
    import_qpipe_rows,
    row_to_knowledge_object,
)
from .sweep import (
    GcSweepBatchResult,
    GcSweepCandidate,
    GcSweepDisposition,
    GcSweepRecord,
    GcSweepState,
)
from .transport import (
    TRANSPORT_VERSION,
    D1KnowledgeIndexRecord,
    KnowledgeCacheRef,
    KnowledgeTransportRequest,
    KnowledgeTransportResponse,
    QueryCacheEnvelope,
    R2BodyDescriptor,
    TransportAuthContext,
    TransportError,
    TransportErrorCode,
    TransportOperation,
    VectorizeMetadata,
)

__all__ = [
    "InMemoryKnowledgeStore",
    "KnowledgeObject",
    "KnowledgeStore",
    "RetrievalRequest",
    "RetrievalResult",
    "IngestionJob",
    "IngestionPipeline",
    "IngestionStatus",
    "CFPlan",
    "CFPrimitive",
    "CFRow",
    "CloudflareBindingAdapter",
    "CloudflareKnowledgeStore",
    "MockCloudflareBindings",
    "cache_key_for",
    "hash_topic",
    "object_to_row",
    "r2_blob_key_for",
    "GcDryRunReport",
    "GcObjectDisposition",
    "GcObjectRecord",
    "GcReconciliationState",
    "KnowledgeBlobRow",
    "R2InventoryObject",
    "GcDeleteFinalizeDecision",
    "GcDeleteLease",
    "GcDeleteLeaseAuthority",
    "GcDeleteLeaseDecision",
    "GcDeleteLeaseResult",
    "GcDeleteLeaseState",
    "GcReferenceDecision",
    "GC_LEASE_SCHEMA_VERSION",
    "GC_LEASE_TABLE",
    "GC_LEASE_ACQUIRE_SQL",
    "GC_LEASE_SCHEMA_SQL",
    "GC_LEASE_SELECT_SQL",
    "GC_LEASE_REFERENCE_COUNT_SQL",
    "GC_LEASE_UPSERT_SQL",
    "GC_LEASE_VALIDATE_SQL",
    "GC_LEASE_WRITER_BLOCK_SQL",
    "gc_lease_schema_statements",
    "D1PreparedStatementBinding",
    "D1DatabaseBinding",
    "D1GcLeaseStore",
    "GcSweepBatchResult",
    "GcSweepCandidate",
    "GcSweepDisposition",
    "GcSweepRecord",
    "GcSweepState",
    "sha256_hex",
    "now_epoch",
    "QPIPE_COMPATIBILITY_SOURCE_REVISION",
    "QPIPE_COMPATIBILITY_SOURCE_BLOBS",
    "ImportPolicy",
    "ImportReport",
    "QPipeRow",
    "QPipeSource",
    "QPipeStatus",
    "derive_authority",
    "import_qpipe_rows",
    "row_to_knowledge_object",
    "TRANSPORT_VERSION",
    "TransportOperation",
    "TransportErrorCode",
    "TransportAuthContext",
    "KnowledgeTransportRequest",
    "TransportError",
    "KnowledgeTransportResponse",
    "D1KnowledgeIndexRecord",
    "R2BodyDescriptor",
    "VectorizeMetadata",
    "KnowledgeCacheRef",
    "QueryCacheEnvelope",
]
